### PR TITLE
Nested rules

### LINKED ISSUE #41: Exit early from "then" rule
An object return rule will exit early with a value.
```js
const rules = [
  {
    return: '"blue"',
  },
  { return: '"green"' },
];

const result = ruleFactory(rules)();
console.log(result); // blue
```
But it will not work inside a "then" rule.
```js
const rules = [
  {
    if: 'true == true',
    then: {
      return: '"blue"',
    },
  },
  { return: '"green"' },
];

const result = ruleFactory(rules)();
console.log(result); // green
```
A string return rule can return a value but will not exit early.
```js
const rules = ['return "blue"', 'return "green"'];

const result = ruleFactory(rules)();
console.log(result); // green
```
Note: "return" is not currently an operator in our expression language. Try replacing "return" with "NickCage" if you don't believe me 😛 Unless.. Wait, @justsml did you alias "return" with "NickCage"?!

 In situations where we have many "if" rules but consider our operation done after any one of them is triggered, the ability to exit early with a literal value from a "then" rule would reduce cognitive overhead by eliminating an intermediate variable and simplifying our mental model. Consider this example adapted from @dara-rockwell 's recent issue.
```js
const things = [
  {
    name: 'ABC',
  },
  {
    name: 'DEF',
  },
  {
    name: 'GHI',
  },
  {
    name: 'JKL',
  },
];

const thingRules = [
  {
    if: 'STRING_CONTAINS("A", thing.name)',
    then: 'keep = false',
  },
  {
    if: 'STRING_CONTAINS("E", thing.name)',
    then: 'keep = false',
  },
  {
    if: 'STRING_CONTAINS("L", thing.name)',
    then: 'keep = false',
  },
  {
    return: 'keep',
  },
];

const filterWithRules = ruleFactory(thingRules);

function isFiltered(thing) {
  const result = filterWithRules({
    thing,
    keep: true,
  });
  return result;
}

console.dir(things.filter(isFiltered)); // [ { name: 'GHI' } ]
```
Now imagine that instead of 3 if statements it was 100. Even if we know that a particular element will trigger the first if statement we still have to look through the other 99 to know what result to expect. If we can exit early with a literal value the code is subtly changed but much easier to manage.
```js
const things = [
  {
    name: 'ABC',
  },
  {
    name: 'DEF',
  },
  {
    name: 'GHI',
  },
  {
    name: 'JKL',
  },
];

const thingRules = [
  {
    if: 'STRING_CONTAINS("A", thing.name)',
    then: 'return false',
  },
  {
    if: 'STRING_CONTAINS("E", thing.name)',
    then: 'return false',
  },
  {
    if: 'STRING_CONTAINS("L", thing.name)',
    then: 'return false',
  },
  {
    // or just 'return true'
    return: 'true',
  },
];

const filterWithRules = ruleFactory(thingRules);

function isFiltered(thing) {
  const result = filterWithRules({
    thing,
  });
  return result;
}

console.dir(things.filter(isFiltered)); // should be [ { name: 'GHI' } ]
```

### LINKED ISSUE #42: Support nested rules
Or error on nested object style (currently only fails on nested array list.)

### PR DESCRIPTION
**Pull request by chhatch**
Closes: [Support nested rules](https://github.com/elite-libs/rules-machine/issues/42)
Also Closes: [Exit early from "then" rule](https://github.com/elite-libs/rules-machine/issues/41)

Support for nested then, else, try, and catch
Includes unmerged changes from [Try stuff, throw stuff, catch stuff.](https://github.com/elite-libs/rules-machine/pull/44)

### CODE REVIEW

File: src/index.ts [hunk 1]
```diff
@@ -75,76 +76,62 @@ export function ruleFactory<
     const getReturnValue = () => results.lastValue;
 
     const startTime = performance.now();
-    if (trace) logTrace({ operation: 'begin', startTime });
+    logTrace({ operation: 'begin', startTime });
```
Comment (chhatch) [inline src/index.ts]: The `if (trace)` is handled by `logTrace`.

Comment (justsml) [reply src/index.ts]: Usually the reason I do this is to avoid any expensive processing (`stringify`) that is passed to `logTrace`.
That doesn't appear to be the case here. 👍

File: src/index.ts [hunk 2]
```diff
@@ -406,17 +392,25 @@ export function extractValueOrLiteral<
...
+  }
   | {
-      and: Rule[];
-    }
+    and: And
+  }
   | {
-      or: Rule[];
-    }
+    or: Or
```
Comment (justsml) [inline src/index.ts]: Nailed it! 🔥

**Review by justsml — APPROVED** [review]
:shipit:

File: src/index.ts [hunk 3]
```diff
@@ -249,42 +232,40 @@ export function ruleFactory<
...
+          handleRule(rule.catch);
         }
       }
+    };
+
+    rules = arrayify(rules);
+
+    for (const rule of rules) {
+      try {
+        handleRule(rule);
```
Comment (justsml) [inline src/index.ts]: Could we rely on a `return` result, rather than try/catch for both errors & early exits?

```ts
for (const rule of rules) {
  try {
    const result = handleRule(rule);
    if (result === 'break') break;
  } catch (error) {
    // add logTrace
    throw error;
  }
}

File: src/index.ts [hunk 4]
```diff
@@ -410,18 +392,25 @@ export function extractValueOrLiteral<
...
   | string
   | {
-    if: Rule
+    if: And | Or | string
     then: Rule
     else?: Rule
   }
   | {
-    and: Rule[]
+    and: And
```
Comment (justsml) [inline src/index.ts]: I think this might be doubling the `{and: {and` bit.

File: src/index.ts [hunk 5]
```diff
@@ -410,18 +392,25 @@ export function extractValueOrLiteral<
...
   | {
-    or: Rule[]
+    or: Or
   }
   | {
-    return: Rule
+    return: string | string[]
   }
   | { try: Rule, catch: Rule }
   | Rule[];
```
Comment (justsml) [inline src/index.ts:400]: I like where you're going here!

If we keep refining these types, I imagine the top-level rules could look like this:

```ts
export type Rule =
  | string
  | IfThenElseRule
  | AndRule
  | OrRule
  | ReturnRule
  | TryCatchRule
  | Rule[];

type RulesStrings = string | string[];
 
interface ReturnRule {
  return: RulesStrings
}

interface TryCatchRule { try: Rule, catch: Rule }

interface IfThenElseRule {
  if: AndRule | OrRule | string
  then: Rule
  else?: Rule
}
```

File: src/index.ts [hunk 6]
```diff
@@ -249,42 +232,40 @@ export function ruleFactory<
           stepRow,
           stepCount,
         });
-        break;
-      } else if ('try' in rule) {
+        // eslint-disable-next-line @typescript-eslint/no-throw-literal
+        throw BREAK;
```
Comment (justsml) [inline src/index.ts]: Maybe return something here instead? So errors don't get mixed in with a success path.

**Review by justsml — APPROVED** [review]
Fantastic work Chris! 🔥 🚀

Left a few comments - lemme know if you think we should get changes in now? Or make a follow up PR?

File: src/index.ts (hunk 4 above)
Comment (chhatch) [reply src/index.ts]: "might be" 🤣 You're too kind.

**Review by justsml — APPROVED** [review]
